# Generated by Django 4.1.13 on 2024-01-04 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectwaysapp', '0002_documentation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='feedback_attachments/')),
                ('priority', models.CharField(choices=[('P3', 'Low (P3)'), ('P2', 'Minor (P2)'), ('P1', 'Major (P1)'), ('P0', 'Critical (P0)')], max_length=2)),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
